---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: abathursa
  namespace: prod

---
# TODO(mierdin): This could probably use some pruning
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: abathurrole
# rules:
# - apiGroups:
#   - ""
#   - "extensions"
#   - "customresourcedefinitions"
#   resources:
#   - pods
#   - services
#   - networks
#   - namespaces
#   - customresourcedefinitions
#   verbs:
#   - create
#   - list
#   - get
#   - delete
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: abathur-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: abathurrole
subjects:
  - kind: ServiceAccount
    name: abathursa
    namespace: prod

