---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: syringesa
  namespace: prod

---
# TODO(mierdin): This could probably use some pruning
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syringerole
# rules:
# - apiGroups:
#   - ""
#   - "extensions"
#   - "customresourcedefinitions"
#   resources:
#   - pods
#   - services
#   - networks
#   - namespaces
#   - customresourcedefinitions
#   verbs:
#   - create
#   - list
#   - get
#   - delete
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: syringe-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: syringerole
subjects:
  - kind: ServiceAccount
    name: syringesa
    namespace: prod


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: syringe
  namespace: prod
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template: 
    metadata:
      name: syringe
      labels:
        app: syringe
        antidote_role: infra
    spec:
      initContainers:
      - name: git-clone
        image: antidotelabs/githelper
        args:
        - "https://github.com/nre-learning/antidote.git"
        - "v0.3.0"  #revme
        - "/antidote"
        volumeMounts:
        - name: git-volume  #?
          mountPath: /antidote

      # Might need an admission controller for this
      serviceAccount: syringesa
      containers:
      - name: syringe
        image: antidotelabs/syringe:release-v0.3.0  #revme
        imagePullPolicy: Always
        env:
        - name: SYRINGE_DOMAIN
          value: labs.networkreliability.engineering
        - name: SYRINGE_LESSONS
          value: "/antidote/lessons"
        - name: SYRINGE_TIER
          value: "prod"
        - name: SYRINGE_LESSON_REPO_REMOTE
          value: "https://github.com/nre-learning/antidote.git"
        - name: SYRINGE_LESSON_REPO_BRANCH
          value: "v0.3.0"  #revme
        - name: SYRINGE_LESSON_REPO_DIR
          value: "/antidote"
        ports:
        # Only accessible from within the container
        # - containerPort: 50099  # GRPC
        - containerPort: 8086   # REST/HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 8086
        volumeMounts:
          - mountPath: /antidote
            name: git-volume
      volumes:
        - name: git-volume
          emptyDir: {}

# /var/run/secrets/kubernetes.io/serviceaccount

# kubectl create serviceaccount syringesa
# kubectl describe serviceaccount syringesa
# kubectl get secret syringesa-token-hjdjv -oyaml

---
kind: Service
apiVersion: v1
metadata:
  name: syringe
  namespace: prod
spec:
  selector:
    app: syringe
  ports:
    # # Only accessible from within the container
    # - name: grpc
    #   port: 50099
    #   targetPort: 50099
    #   # nodePort: 30010
    - name: http
      port: 8086
      targetPort: 8086
      # nodePort: 30011
  type: ClusterIP
  # type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/
    ingress.kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-services: "syringe"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/limit-connections: "10"
    nginx.ingress.kubernetes.io/limit-rps: "5"
  name: syringe
  namespace: prod
spec:
  tls:
    - hosts:
      - labs.networkreliability.engineering
      - maintbypass.labs.networkreliability.engineering
      secretName: tls-certificate
  rules:
  - host: labs.networkreliability.engineering
    http:
      paths:
      - path: "/syringe"
        backend:
          serviceName: syringe
          servicePort: 8086
  - host: maintbypass.labs.networkreliability.engineering
    http:
      paths:
      - path: "/syringe"
        backend:
          serviceName: syringe
          servicePort: 8086

