
- name: Restart kubelets
  hosts: all
  gather_facts: no
  become: yes
  vars:
    ansible_user: root 
  tasks:

  - name: Restart kubelet service
    systemd:
      name: kubelet
      state: restarted
      daemon_reload: yes
      enabled: True
