---
name: autodeploy-ptr-syringe
description: Deploy latest changes of Syringe to PTR
trigger:
  type: git.head_sha_monitor
criteria:
  trigger.repository_url:
    pattern: https://github.com/nre-learning/syringe.git
    type: equals
  trigger.branch:
    pattern: master
    type: equals
action:
  ref: antidoteops.deploy
  parameters:
    version: latest
    tier: ptr
enabled: true
