---
name: tweet_new_content_mierdin
description: Tweet new content from @Mierdin
trigger:
  type: antidoteops.new_content
criteria:
    trigger.link:
        type: "contains"
        pattern: "keepingitclassless.net"
action:
  ref: antidoteops.tweet_new_content
  parameters:
    account: mierdin
    link: "{{ trigger.link }}"
    featuredimage: "{{ trigger.featuredimage }}"
    title: "{{ trigger.title }}"
    timeout: 604800
enabled: true
