---
name: tweet_new_content_nrelabs
description: Tweet new content from @NRELabs
trigger:
  type: antidoteops.new_content
criteria:
    trigger.link:
        type: "contains"
        pattern: "networkreliability.engineering"
action:
  ref: antidoteops.tweet_new_content
  parameters:
    account: nrelabs
    link: "{{ trigger.link }}"
    featuredimage: "{{ trigger.featuredimage }}"
    title: "{{ trigger.title }}"
    rtaccounts: ["mierdin"]
enabled: true
